name: joshkilen
favicon: null
layout_spectrum: 0.4755700391251594
typography_spectrum: 0.1699244154151529
title: "Josh Kilen's Collection of Curious Content"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1391476015560329
  lightness: 0.2935747921001166
  saturation: 0.7323993509635329
  rhythmicContrast: 0.9418152100406587
purpose: []
